library(bslib)
library(leaflet)
library(leafgl)
library(data.table)
library(sf)
library(shinyWidgets)
library(highcharter)
library(shinyjs)
# shinyWidgets::shinyWidgetsGallery()
# webshot::install_phantomjs()

options(shiny.fullstacktrace=TRUE)
